version: "3"
services:
  web:
    image: wordsbaking-api
    depends_on:
      - mongo
    ports:
      - 8080:80
    networks:
      - webnet
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - wordsbaking-mongo-db-data:/data/db
    networks:
      - webnet
networks:
  webnet:
volumes:
  wordsbaking-mongo-db-data:
    external: true
